name: Report incorrect Data
description: Report incorrect data about existing Airsoft guns in the database.
labels:
  - bug
body:
  - type: input
    attributes:
      label: Database Version (or Date)
      description: You can find the version info in Menu - Settings of AIRSOFT SPOTTER app.
  - type: input
    attributes:
      label: Brand Name
    validations:
      required: true

  - type: input
    attributes:
      label: Airsoft Gun Name
    validations:
      required: true

  - type: dropdown
    id: power-source
    attributes:
      label: Power Source
      options:
        - Spring
        - Battery
        - Gas
        - Other
    validations:
      required: true

  - type: dropdown
    id: power-level
    attributes:
      label: Is it low-power model ?
      description: If you are not sure, please select "No".
      options:
        - "No"
        - Yes (less than 0.5J)
        - Yes R10+ (JPN)
        - Yes R14+ (JPN)
      default: 0
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is wrong with the data ?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Do you have a data source ?
      description: URL of product page is strongly recommended.
    validations:
      required: false