# .github/workflows/validate-csv.yml
name: Validate CSV Data

on:
  pull_request:
    branches: [ main ] # Triggered on pull requests targeting the main branch

jobs:
  validate:
    name: Validate CSV Files
    runs-on: ubuntu-latest # Specifies the execution environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Sets up the Node.js environment
        with:
          node-version: '20' # Uses Node.js v20 as specified in README.md
          cache: 'npm' # Enables npm dependency caching

      - name: Install dependencies
        run: npm install # Installs dependencies based on package.json

      - name: Run database validation script
        run: npm run test-database # Executes the CSV validation script 